services:
  cache_links_redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - 6379:6379