"""fix table users

Revision ID: c1afc920d0c8
Revises: cebde54d132a
Create Date: 2025-06-26 20:16:34.147701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1afc920d0c8"
down_revision: Union[str, None] = "cebde54d132a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "tg_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "tg_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
