"""fix2 table links

Revision ID: 81c5f5c48407
Revises: 6ab4b3bbe564
Create Date: 2025-06-28 19:35:52.622453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c5f5c48407"
down_revision: Union[str, None] = "6ab4b3bbe564"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "links", sa.Column("short_link", sa.String(), nullable=False)
    )
    op.create_unique_constraint(None, "links", ["short_link"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "links", type_="unique")
    op.drop_column("links", "short_link")
    # ### end Alembic commands ###
